

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


gem "rspec", "~> 3.10"
gem "colorize", "~> 0.8.1"
gem "tty-prompt"
gem 'terminal-table', '~> 3.0', '>= 3.0.1'
gem 'artii'